name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: yarn install
      # - name: Lint
        # run: yarn eslint --ext .js,.jsx src
      # - name: Run unit tests
      #   run: npm run test:unit
      - name: Build
        run: |
          yarn build:prod
          cp dist/index.html dist/404.html

      - name: Deploy to GitHub Pages
        run: yarn deploy

      - name: Clean up repository
        run: rm -rf dist
